### PR TITLE
[544] Skip 2nd level dependency flag

### PR DESCRIPTION
**Pull request by loregr**

### CODE REVIEW

**Comment by mmiedlarz** [comment]
I think that there is simpler solution, by not passing dataMapper for Gallery and Partner application in: `DataIncludeMapperDefaultParser`. AFAIK API does not send 2nd level relationships at all now, so probably we can even ignore all `dataMapper` parameters there.

We're doing same thing for User <-> CustomStyle relationship right now.

**Comment by loregr** [comment]
@mmiedlarz yeah, that was my initial idea, but there may be some cases were we have the 2nd level relationships indirectly available in the `included` response, and it will cause an infinite loop. (i.e. recent content has different galleries in its list, one of them is connected to a partner application that is connected to a provided gallery as well)

**Review by mmiedlarz — APPROVED** [review]
Looks great 👍

**Review by DaDer — APPROVED** [review]
👍 Great to have this option

**Pull request merged**
