### PR TITLE
possibly fix crash in realm config seen in sentry.io

### PR DESCRIPTION
**Pull request by coolbnjmn**
Fixing sentry.io crash found.
Example crash in Sentry: https://sentry.io/creatubbles/ctb-ios/issues/420184087/

There are several others that are seemingly crashing at the same spot.

### CODE REVIEW

**Comment by coolbnjmn** [comment]
After `get building` commit, I'm not sure if that's the fix we want or not. I'm also not convinced we need realm for what we're using it for (although I think Realm is very useful and we should use it to cache stuff).

I think @mmiedlarz you probably have the best context on it's implementation? Would love to have a chat with you about how we're using Realm and if this solution makes sense to you :).

**Review by mmiedlarz — COMMENTED** [review]
I love an idea of optional realm instance, however in this solution we won't know if we spot any issue with saving uploadSession to DB (I guess that app will just not start upload instead of crashing in this solution). 

I'd suggest to mark all methods with `realm?.` to throwing ones, and handle errors on higher level (I can take care of this if you want).

**Comment by mmiedlarz** [comment]
@coolbnjmn 
> After get building commit, I'm not sure if that's the fix we want or not. I'm also not convinced we need realm for what we're using it for (although I think Realm is very useful and we should use it to cache stuff).

Yeah, I love realm :D but I also see your point. Realm is getting more problematic (specially with it's binary size), so we might start looking for a new persistence lib (mostly for something lighter than realm, we just need to store some stuff from time to time)

**Comment by mmiedlarz** [comment]
I think it might be good to wait for @DaDer's fixes to upload flow. Seems that it'll be huge boost for our upload "engine".

**Comment by coolbnjmn** [comment]
Ok, I'm going to close this PR for now (I just wanted to learn more about how we're using Realm) because I want to get the right fix in, not just a quick fix. 

Also, saw your mention of sentry.io only working for APIClient, I'll follow up with you on that in Slack :).

**Pull request closed without merging**
