### PR TITLE
add users and galleries to bubble state check function

### PR DESCRIPTION
**Pull request by coolbnjmn**
Fix for: https://trello.com/c/3aJtmOGO

### CODE REVIEW

**Comment by coolbnjmn** [comment]
[User should see a bubbled user marked as bubbled on that user's profile and should not be able to attempt to bubble that user again](https://trello.com/c/3aJtmOGO/466-user-should-see-a-bubbled-user-marked-as-bubbled-on-that-users-profile-and-should-not-be-able-to-attempt-to-bubble-that-user-aga)

**Review by mmiedlarz — APPROVED** [review]
Code 👍  
gallery/creation/user identifiers are unique right?
I mean - user identifiers are always different from gallery/creation identifiers (and vice-versa).

**Comment by DaDer** [comment]
Good question @mmiedlarz if the backend team is not using UUID for all primary keys IMO it's not unique

**Comment by coolbnjmn** [comment]
I have confirmed with backend team that this ID is unique across all 3 object types.

**Review by DaDer — APPROVED** [review]
👍

**Pull request merged**
