### PR TITLE
[CRI-1192] fix crashes and a chunk of the file

### PR DESCRIPTION
**Pull request by coolbnjmn**
https://nomtek.atlassian.net/browse/CRI-1192

### CODE REVIEW

**Comment by mmiedlarz** [comment]
I don't see connection between changes in DAO and crashlog from Fabric. Were you able to reproduce issue?
Also I'm not sure how new `ErrorCancelable` will be handled in production code, and missing DAO for me is a kind of error which should crash app.

**Comment by coolbnjmn** [comment]
Looking at the raw crash log from Fabric, which I've copied here for convenience:
```
0  CreatubblesBase                0x101c4e27c specialized FastCollectionViewControllerBaseDataSource.(fastCollectionView(FastCollectionViewController, reloadDataForItemAtIndexPath : IndexPath, completion : () -> ()) -> ()).(closure #1) (FastCollectionViewControllerBaseDataSource.swift)
1  CreatubblesBase                0x101c4921c FastCollectionViewControllerBaseDataSource.(fastCollectionView(FastCollectionViewController, reloadDataForItemAtIndexPath : IndexPath, completion : () -> ()) -> ()).(closure #1) (FastCollectionViewControllerBaseDataSource.swift)
2  CreatubblesBase                0x101caf4bc specialized CreationDAO.(getCreation(creationIdentifier : String, completion : (Creation?, Error?) -> ()?) -> RequestHandler).(closure #1) (CreationDAO.swift)
3  CreatubblesBase                0x101caf128 CreationDAO.(getCreation(creationIdentifier : String, completion : (Creation?, Error?) -> ()?) -> RequestHandler).(closure #1) (CreationDAO.swift)
4  CreatubblesAPIClient           0x1002acb54 specialized CreationsDAO.(getCreation(creationIdentifier : String, completion : (Creation?, APIClientError?) -> ()?) -> RequestHandler).(closure #1) (CreationsDAO.swift)
5  CreatubblesAPIClient           0x1002ab618 partial apply for CreationsDAO.(getCreation(creationIdentifier : String, completion : (Creation?, APIClientError?) -> ()?) -> RequestHandler).(closure #1) (CreationsDAO.swift)
6  CreatubblesAPIClient           0x1002effec partial apply for FetchCreationsResponseHandler.(handleResponse([String : AnyObject]?, error : Error?) -> ()).(closure #3) (FetchCreationsResponseHandler.swift)
```

it's easy to see that *something* around CreationDAO isn't going properly right -- I found a bunch of force unwraps, which when looking at it, made sense as a possible cause of this. For that reason, I went about optionally unwrapping the assemblies. I 100% agree that it SHOULD be there, but in production, sometimes shit isn't there (annoying, right?) when it should be, but we don't need to crash the app there (that's a bad user experience) (UNLESS it's staging/debug, in which case we want to have it crash to know and fix it). The way we do that is `assertionFailure` and debug logs, which is what this PR attempts to do without changing the external API of the APIClient at all. 

If you think there's a better/cleaner method, I'm more than happy to refactor this PR, because I'm sure there is haha. LMK @mmiedlarz

**Comment by mmiedlarz** [comment]
Yeah, but in terms of missing DAO, shouldn't we rather get message which pointed force unwrap directly (similar to issue in `PartnerApplication`).

**Comment by mmiedlarz** [comment]
> If you think there's a better/cleaner method, I'm more than happy to refactor this PR, because I'm sure there is haha

Hmm... I think I have an idea. I was worried about FCVC which may not handle this case, but I think that calling completion block with predefined error should do the trick (and returning error completion handler).
Something like this:
```swift
guard let assembly = daoAssembly.assembly(CreationsDAO.self) 
else {
    assertionFailure("Need valid assembly for RequestHandler return")
    completion?(nil, APIClientError.MissingDAOError(type: GalleryDAO.self))    
    return RequestHandler(object: ErrorCancelable())
}
```

**Comment by coolbnjmn** [comment]
Ok... @mmiedlarz do you want to add a commit to this PR then? Or what is the idea? As much as possible, the way I see it is force unwraps are sources for crashes. Even if we KNOW 100% for sure that a value is supposed to be there, in production the saying holds true of **"shit happens"** and so it's just better to not have them and properly raise errors. It sounds like you have an idea to that effect though, but let me know if you want me to implement or if you are :)

**Comment by mmiedlarz** [comment]
Hmmm... I'm not sure how FCVC will handle this case (infinite page load?) I really prefer to have this feature checked and tested before release.

**Comment by coolbnjmn** [comment]
What do you mean by `how FCVC will handle this case **(infinite page load?)**` *?* not sure what that highlighted portion refers to, could you elaborate? @mmiedlarz

**Comment by mmiedlarz** [comment]
I'm not sure what FCVC will do in case of error page. I'm worried that it'll try to fetch it infinitely.
I don't know when it could happen, but I'm just generalizing.

**Pull request closed without merging**
